name: Build Android APK
on:
  push:
    branches:
      - main  # Veya 'master', ana dalınızın adı neyse

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Buildozer önbelleğini kullanarak sonraki buildleri hızlandırır
      - name: Cache Buildozer Global Directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache Buildozer Directory
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

      # Build işlemini başlatan ana eylem
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      # Oluşan APK dosyasını GitHub'a yükle (İndirebilmeniz için)
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CheatSimulator-APK
          path: bin/*.apk
          retention-days: 5  # Dosya 5 gün sonra silinir
